[build]
    command = "npm run build"
    publish = "build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
  from = "/proxy-image/*"
  to = "https://storage.googleapis.com/:splat"
  status = 200
